import System.Random

loop n = do
    putStrLn "please guess the number"
    l <- getLine
    let i = read l :: Int
    if i == n
    then putStrLn "You GUESSED it congratulations!!!!"
    else  if i > n
          then do
                 putStrLn "Too High"
                 loop n
          else do
                putStrLn  "Too Low"
                loop n

main=do

        putStrLn "in this game you will have to guess a number generated by the computer between 1 and 16 So lets START!!!"

        g <- randomRIO (1,16)
       -- print (g::Int)
        loop g






