import System.Random

loop n tries = do
    putStrLn "please guess the number"
    l <- getLine
    let i = read l :: Int
    if i == n
    then putStrLn $ "You GUESSED it in " ++ show tries ++ " tries. Congratulations!!!!"
    else  if i > n
          then do
                 putStrLn "Too High"
                 loop n (tries+1)
          else do
                putStrLn  "Too Low"
                loop n (tries+1)

main=do

        putStrLn "in this game you will have to guess a number generated by the computer between 1 and 16 So lets START!!!"

        g <- randomRIO (1,16)
       -- print (g::Int)
        loop g 1






